dnw/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from portfolio import urls as portfolio_urls


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^portfolio/', include(portfolio_urls, namespace="portfolio")),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.conf.urls import patterns, url

from .views import PortfolioListView, PortfolioDetailView


urlpatterns = patterns('portfolio.views',
    url(r'^$',
        PortfolioListView.as_view(),
        name="list"),
    url(r'^(?P<slug>[\w.,/_\-]+)/$',
        PortfolioDetailView.as_view(),
        name='detail'),
)

portfolio/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from model_utils.models import TimeStampedModel, StatusModel
from model_utils import Choices
from autoslug import AutoSlugField


@python_2_unicode_compatible
class Portfolio(TimeStampedModel, StatusModel):
    """
    Portfolio model stores information about completed
    projects
    """
    STATUS = Choices('draft', 'published')
    PROPERTY_CHOICES = Choices('residential', 'commericial', 'community')

    title = models.CharField(max_length=128)
    slug = AutoSlugField(populate_from='title')
    property_type = models.CharField(choices=PROPERTY_CHOICES,
                                     default=PROPERTY_CHOICES.residential,
                                     max_length=64)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

    def featured_image(self):
        return self.images.filter(featured=True).first()


@python_2_unicode_compatible
class PortfolioImage(TimeStampedModel):
    portfolio = models.ForeignKey(Portfolio, related_name='images')
    title = models.CharField(max_length=128)
    file_path = models.ImageField(upload_to='portfolio',
                                  blank=True, null=True)
    front_page = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    order = models.IntegerField(default=0)

    def __str__(self):
        return "{}: {}".format(self.portfolio.title,
                               self.title)

portfolio/views.py
from django.views.generic import ListView, DetailView

from .models import Portfolio


class PortfolioListView(ListView):
    model = Portfolio
    template_name = 'portfolio/list.html'
    context_object_name = 'portfolio'
    queryset = Portfolio.published.all()


class PortfolioDetailView(DetailView):
    model = Portfolio
    template_name = 'portfolio/detail.html'
    context_object_name = 'project'

templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Designs Northwest Architects{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="">

    {% block css %}
    <!-- Latest minified Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/designsnw.css' %}" rel="stylesheet">
    {% endblock %}

    <!-- Google Analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-71204146-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>

  <body>
    {% block pre-content %}{% endblock pre-content %}
    <div class="container">

    <div class="col-md-6 col-md-offset-3">
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}
    </div>

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->

      <!-- Third-party libraries -->

      <!-- place project specific Javascript in this file -->
    {% endblock javascript %}
  </body>
</html>

templates/portfolio/detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="row">
    <h1>{{ project.title }}</h1>
    <h3>{{ project.property_type }}</h3>
    <p>{{ project.description }}</p>

    {% for image in project.images.all %}
    <section class="col-md-4">
        <a class="thumbnail" href="#"><img src="{{ MEDIA_URL }}/{{ image.file_path }}" alt="{{ image.title }}" /></a>
    </section>
    {% endfor %}
</div>
{% endblock content %}

templates/portfolio/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="row">
    <h1>Portfolio</h1>
    {% for project in portfolio %}
    <section class="col-md-4">
        <a class="thumbnail" href="{% url 'portfolio:detail' project.slug %}"><img src="{{ MEDIA_URL }}/{{ project.featured_image.file_path }}" alt="{{ project.featured_image.title }}" /></a>
        <h2>{{ project.title }}</h2>
    </section>
    {% endfor %}
</div>
{% endblock content %}